apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: APP_NAME
  description: The name for the application
  displayName: Application Name
  required: true
  value: unhealthy-sky
- name: WELCOME_IMAGE_NAME
  description: The Welcome App's image name
  displayName: Image Name
  required: true
  value: fabric8/launcher-creator-welcome-app
- name: WELCOME_IMAGE_TAG
  description: The Welcome App's image tag
  displayName: Image Tag
  required: true
  value: latest
- name: WELCOME_APP_CONFIG
  description: The configuration for the welcome app
  displayName: Welcome App Configuration
  required: true
  value: |-
    {
      "parts": [{
        "capabilities": [{
          "module": "capability-health",
          "props": {},
          "extra": {
            "category": "backend"
          }
        }, {
          "module": "capability-welcome",
          "props": {},
          "extra": {
            "category": "support"
          }
        }],
        "shared": {
          "runtime": {
            "name": "dotnet",
            "version": "community"
          },
          "dotnet": {
            "namespace": "MyApp",
            "version": "1.0.0"
          }
        },
        "extra": {
          "runtimeInfo": {
            "enumInfo": {
              "id": "dotnet",
              "name": ".NET Core",
              "description": "Create stand-alone, production-grade .NET Core Applications that you can \"just run\".",
              "icon": "data:image/svg+xml;charset=utf8,%3Csvg version='1.1' id='Layer_1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0 32 32' style='enable-background:new 0 0 32 32;' xml:space='preserve'%3E%3Cstyle type='text/css'%3E .st0%7Bfill:%23008CDB;%7D%0A%3C/style%3E%3Cpath class='st0' d='M32,9.56h-8.72v1.28h3.59V22h1.53V10.84H32V9.56z M21.81,10.84V9.56h-6.66V22h6.66v-1.28h-5.12v-4.34h4.56 v-1.31h-4.56v-4.22H21.81z M2.16,21.41c0,0.29-0.1,0.54-0.31,0.75s-0.47,0.31-0.78,0.31c-0.29,0-0.54-0.1-0.75-0.31 C0.1,21.95,0,21.7,0,21.41c0-0.31,0.1-0.57,0.31-0.78s0.46-0.31,0.75-0.31c0.31,0,0.57,0.1,0.78,0.31S2.16,21.09,2.16,21.41 L2.16,21.41z M13.41,9.56h-1.53v9.81l-7-9.81H3.34V22h1.53v-9.81L11.91,22h1.5V9.56z'/%3E%3C/svg%3E%0A",
              "metadata": {
                "categories": ["backend"],
                "language": "csharp",
                "website": "https://docs.microsoft.com/en-us/dotnet/core"
              }
            },
            "image": "registry.access.redhat.com/dotnet/dotnet-22-rhel7",
            "service": "unhealthy-sky",
            "route": "unhealthy-sky"
          },
          "category": "backend"
        }
      }],
      "application": "unhealthy-sky"
    }
- name: FRONTEND_SERVICE_NAME
  description: The frontend service name for the welcome app
  displayName: Frontend service name
  required: true
  value: unhealthy-sky
- name: BACKEND_SERVICE_NAME
  description: The backend service name for the welcome app
  displayName: Backend service name
  required: true
  value: unhealthy-sky
- name: SOURCE_REPOSITORY_PROVIDER
  description: The source repository provider
  displayName: Source Provider
  value: GitHub
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
- name: OPENSHIFT_CONSOLE_URL
  description: The OpenShift Console URL for the application
  displayName: OpenShift Console URL
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: ${WELCOME_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}-welcome
      spec:
        containers:
        - image: ${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}
          name: ${APP_NAME}-welcome
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 8M
            limits:
              cpu: 50m
              memory: 100Mi
          env:
          - name: WELCOME_APP_CONFIG
            value: ${WELCOME_APP_CONFIG}
          - name: OPENSHIFT_CONSOLE_URL
            value: ${OPENSHIFT_CONSOLE_URL}
          - name: SOURCE_REPOSITORY_PROVIDER
            value: ${SOURCE_REPOSITORY_PROVIDER}
          - name: SOURCE_REPOSITORY_URL
            value: ${SOURCE_REPOSITORY_URL}
          - name: FRONTEND_SERVICE_NAME
            value: ${FRONTEND_SERVICE_NAME}
          - name: BACKEND_SERVICE_NAME
            value: ${BACKEND_SERVICE_NAME}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}-welcome
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}-welcome:${WELCOME_IMAGE_TAG}
      type: ImageChange
  status:
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    updatedReplicas: 0
    availableReplicas: 0
    unavailableReplicas: 0
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}-welcome
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}-welcome
    labels:
      app: ${APP_NAME}
      creatorCategory: support
    annotations:
      console.alpha.openshift.io/overview-app-route: 'true'
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}-welcome
